// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import globals from 'globals';

/**
 * The rules the site is written against.
 *
 * In the product monorepo this config lives at the root and covers the API, the app and this
 * site together; here it carries only the parts that apply to a Next.js marketing site — the
 * blocks restricting cloud SDKs and persistence imports guard `apps/api`, which is not in this
 * repository. Style is Prettier's job; these rules are about correctness.
 */
export default tseslint.config(
  {
    ignores: [
      '**/.next/**',
      '**/node_modules/**',
      '**/coverage/**',
      '**/playwright-report/**',
      '**/test-results/**',
      // Generated by Next on every dev/build. Its triple-slash references are the file's whole
      // purpose and rewriting them lasts until the next `next dev`.
      'next-env.d.ts',
      // Build-tool config files: outside the tsconfig `include`, so the type-aware parser
      // cannot resolve them. They contain no application logic.
      '**/*.config.mjs',
      '**/*.config.js',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,

  {
    languageOptions: {
      globals: { ...globals.node },
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
    rules: {
      // `any` erases the type system exactly where a mistake is expensive.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unsafe-assignment': 'warn',
      '@typescript-eslint/no-non-null-assertion': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/await-thenable': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/consistent-type-imports': ['error', { prefer: 'type-imports' }],
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],

      // Swallowed errors are how a system loses the ability to tell you it is broken.
      'no-empty': ['error', { allowEmptyCatch: false }],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },

  // Scripts are CLI tools; console output is their interface. Config files are shaped by the
  // framework: `next.config.ts` must declare `async headers()` whether or not it awaits.
  {
    files: ['**/scripts/**/*.ts', '**/*.config.ts', '**/*.spec.ts'],
    rules: {
      'no-console': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/require-await': 'off',
    },
  },

  // Test files, where three rules that are right in production code are wrong here.
  //
  //  - unbound-method: `expect(fn)` is how you assert on a spy. The rule is warning about a
  //    `this` binding the assertion never uses.
  //  - no-non-null-assertion: a test asserts a shape it has just constructed; making it
  //    defensive about its own fixtures obscures what is being tested.
  //  - require-await: an async stub that returns a literal is the clearest way to satisfy a
  //    Promise-returning interface.
  {
    files: ['**/*.spec.ts', '**/test/**/*.ts', 'e2e/**/*.ts'],
    rules: {
      '@typescript-eslint/unbound-method': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/require-await': 'off',
    },
  },
);
