/**
 * Every public route, for the specs that walk all of them.
 *
 * Kept as a literal list rather than derived from the build so that a page silently
 * disappearing from the sitemap does not also silently disappear from the test suite.
 */
export const routes = [
  '/',
  '/product',
  '/product/admissions-and-growth',
  '/product/academics-and-content',
  '/product/delivery-and-engagement',
  '/product/assessment-and-outcomes',
  '/product/money-and-people',
  '/product/intelligence',
  '/product/platform-and-trust',
  '/product/modules/admissions-crm',
  '/product/modules/institute-website',
  '/product/modules/courses-and-curriculum',
  '/product/modules/media-and-content',
  '/product/modules/ai-assistance',
  '/product/modules/learning-delivery',
  '/product/modules/live-classes-and-attendance',
  '/product/modules/batches-and-enrollment',
  '/product/modules/assessments',
  '/product/modules/assignments-and-grading',
  '/product/modules/certificates',
  '/product/modules/fees-and-finance',
  '/product/modules/staff-and-hr',
  '/product/modules/placement-and-interviews',
  '/solutions',
  '/solutions/coaching-institutes',
  '/solutions/schools',
  '/solutions/universities',
  '/solutions/skilling-academies',
  '/solutions/corporate-l-and-d',
  '/pricing',
  '/security',
  '/trust',
  '/trust/build-status',
  '/trust/sub-processors',
  '/trust/dpa',
  '/trust/responsible-disclosure',
  '/accessibility',
  '/developers',
  '/developers/webhooks',
  '/integrations',
  '/compare',
  '/compare/moodle',
  '/compare/google-classroom',
  '/compare/canvas',
  '/compare/spreadsheets-and-whatsapp',
  '/why-akechi',
  '/customers',
  '/resources',
  '/resources/migrating-from-spreadsheets',
  '/resources/rbac-for-schools',
  '/resources/assessment-integrity-without-a-camera',
  '/resources/buying-accessible-software',
  '/resources/self-hosting-akechi',
  '/resources/why-a-pwa',
  '/about',
  '/contact',
  '/demo',
  '/legal/terms',
  '/legal/privacy',
  '/legal/cookies',
  '/legal/acceptable-use',
  '/legal/security-policy',
] as const;

/** The ten that carry the most weight, for the slower checks. */
export const keyRoutes = [
  '/',
  '/product',
  '/pricing',
  '/security',
  '/trust/build-status',
  '/accessibility',
  '/developers',
  '/compare/moodle',
  '/solutions/schools',
  '/demo',
] as const;
